<?php

namespace EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindByLetters($string)
    {
        $query = $this->getEntityManager()->createQuery("SELECT a FROM EventBundle:Event a WHERE (a.titleEvent like :titleEvent)")
            ->setParameter('titleEvent','%'.$string.'%');

        return $query->getResult();
    }
}
