<?php

namespace EventBundle\Repository;

/**
 * InvitationFriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationFriendRepository extends \Doctrine\ORM\EntityRepository
{
}
