<?php

namespace EventBundle\Repository;

/**
 * likeeventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class likeeventRepository extends \Doctrine\ORM\EntityRepository
{
}
