<?php

namespace EventBundle\Repository;

/**
 * participationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participationRepository extends \Doctrine\ORM\EntityRepository
{
}
