<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindByLetters($string)
    {
        $query = $this->getEntityManager()->createQuery("SELECT a FROM BlogBundle:Article a WHERE (a.titreArticle like :titreArticle)")
            ->setParameter('titreArticle','%'.$string.'%');

        return $query->getResult();
    }

}
