<?php

namespace BlogBundle\Repository;

/**
 * commentarticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentarticleRepository extends \Doctrine\ORM\EntityRepository
{
}
