<?php

namespace BlogBundle\Repository;

/**
 * likearticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class likearticleRepository extends \Doctrine\ORM\EntityRepository
{
}
