services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    sarra.form.type.tags:
      class: BlogBundle\Form\TagType
      arguments: ['@doctrine.orm.entity_manager']
      tags:
        - { name:form.type }